language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  only:
    - master
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - links
      - libblas-dev
      - libfftw3-dev
      - libmagic-dev
      - libsnappy-dev
      - libzmq-dev
      - libpq-dev
      - postgresql
      - redis-server
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh deps-macosx ; else ./build.sh deps-apt-get ; fi
  - >
    wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz && tar xzvf v1.7.2.tar.gz &&
    ( cd udis86-1.7.2/ && ./autogen.sh && ./configure --enable-shared=yes && make && sudo make install ) &&
    ( [[ "$TRAVIS_OS_NAME" != "osx" ]] && sudo ldconfig || true )
script: >
  ./build.sh net-bootstrap < /dev/null &&
  mkdir -p mason/builds &&
  ( cd mason/builds && ../../factor -run=mason.test < /dev/null | grep "Loading resource\|Unit Test" ) &&
  ( cd mason && ../factor -e='USING: mason.config mason.report namespaces ; "." builds-dir [ successful-report ] with-variable' ) &&
  ( [[ "$TRAVIS_OS_NAME" != "osx" ]] && links -dump mason/report || cat mason/report ) &&
  [ ! -s mason/test-all-errors ]
