language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  only:
    - master
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - links
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh deps-macosx ; else ./build.sh deps-apt-get ; fi
script: >
  ./build.sh net-bootstrap < /dev/null &&
  mkdir -p mason/builds &&
  ( cd mason/builds && ../../factor -run=mason.test < /dev/null ) &&
  ( cd mason && ../factor -e='USING: mason.config mason.report namespaces ; "." builds-dir [ successful-report ] with-variable' &&
      links -dump report ) &&
  [ ! -s mason/test-all-errors ]
