language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  only:
    - master
sudo: required
dist: trusty
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh deps-macosx ; else ./build.sh deps-apt-get ; fi
script: ./build.sh net-bootstrap < /dev/null
