language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
branches:
  only:
    - master
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - links
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh deps-macosx ; else ./build.sh deps-apt-get ; fi
  - >
    wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz && tar xzvf v1.7.2.tar.gz &&
    ( cd udis86-1.7.2/ && ./autogen.sh && ./configure --enable-shared=yes && make && sudo make install ) &&
    sudo ldconfig
script: >
  ./build.sh net-bootstrap < /dev/null &> bootstrap_log &&
  mkdir -p mason/builds &&
  ( cd mason/builds && ../../factor -run=mason.test &> tests_log < /dev/null ) &&
  ( cd mason && ../factor -e='USING: mason.config mason.report namespaces ; "." builds-dir [ successful-report ] with-variable' &&
      links -dump report ) &&
  cat bootstrap_log && cat mason/builds/tests_log && cat mason/* &&
  [ ! -s mason/test-all-errors ]
