language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
env:
  - FACTOR_TESTS_CHUNK=1/3
  - FACTOR_TESTS_CHUNK=2/3
  - FACTOR_TESTS_CHUNK=3/3
branches:
  only:
    - master
sudo: required
dist: trusty
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./build.sh deps-macosx ; else ./build.sh deps-apt-get ; fi
script: ./build.sh net-bootstrap < /dev/null && ./factor -run=mason.test < /dev/null
